name: HelloWorld
on:
  push:
    branches:
      - develop
jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Output Validation
        run: echo "Hallo Welt"
